### ISSUE TITLE
Add example for EndpointSlice

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/kubernetes-examples#17]
We're missing an example for EndpointSlices, but we do have one for Endpoints. This example could go in the same directory or a new one.

It should be possible to use the example from here: https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/

If you want to pick up this issue, please first read the README.md and CONTRIBUTING.md. Make sure you follow the existing style and standards for other examples.

**Comment by 3t8** [comment]
Working on it

**Comment by 3t8** [comment]
Made a PR
