### ISSUE TITLE
Add example for PersistentVolumeClaim

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/kubernetes-examples#18]
We're missing an example for PersistentVolumeClaim, but we do have one for PersistentVolumes. This example should probably go in the same directory.

It should be possible to use an example from the Kubernetes docs, but please make sure it works either standalone or with the existing PersistentVolume example.

If you want to pick up this issue, please first read the README.md and CONTRIBUTING.md. Make sure you follow the existing style and standards for other examples.

**Comment by sebagomez** [comment]
I'll work on this one
